package com.steelkiwi.dapi_plugin

enum class DapiActions {
    LOGIN,
    CLEAR_LOGIN_LISTENER,
    CREATE_TRANSACTION_ID_TO_ID,
    CREATE_TRANSACTION_ID_TO_I_BAN,
    CREATE_TRANSACTION_ID_TO_NUMBER,
    DELINK,
    GET_BANK_METADATA,
    CREATE_BENEFICIARY,
    GET_SUB_ACCOUNTS,
    GET_ACTIVE_CONNECTION,
    GET_BENEFICIARIES
}