package com.steelkiwi.dapi_plugin

enum class DapiActions {
    INIT,
    LOGIN,
    CLEAR_LOGIN_LISTENER,
    CREATE_TRANSACTION,
    DELINK,
    GET_BANK_METADATA,
    CREATE_BENEFICIARY,
    GET_SUB_ACCOUNTS,
    GET_ACTIVE_CONNECTION,
    GET_BENEFICIARIES
}